LIST_FILE=list.txt
HOST_FILE=hosts

define HOSTS_HEADER
# DO NOT EDIT
# Generated by running `make`
# Source https://github.com/blockall/porn

# Last updated $(shell date +%Y-%m-%d)

127.0.0.1 localhost
127.0.0.1 localhost.localdomain
::1       localhost
255.255.255.255 broadcasthost


# Porn hosts

endef

export HOSTS_HEADER
all:
	sed -i "/^\s*$$/d" $(LIST_FILE)
	sed -i "s~http[s]*://~~g" $(LIST_FILE)
	sed -i "s~/.*~~g" $(LIST_FILE)
	sort -us $(LIST_FILE) -o $(LIST_FILE)
	echo "$$HOSTS_HEADER" > $(HOST_FILE)
	sed -e 's/^/0.0.0.0 /' $(LIST_FILE) >> $(HOST_FILE)

